#!/bin/sh

case "$1" in
    start)
	fbv -d 1 /usr/share/pixmaps/skolar-display-splash.png > /dev/null 2>&1
        echo "done"
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac

exit 0
